#cloud-config
package_update: true
packages:
  - docker.io
  - git

runcmd:
  - systemctl enable docker
  - systemctl start docker

  - git clone https://github.com/katehjd21/endgame_assignment.git /home/ubuntu/app
  - cd /home/ubuntu/app

  - docker build -t endgame-backend ./backend
  - docker rm -f backend-app || true
  - docker run -d --restart always -p 5000:5000 \
      -e DB_USERNAME=${db_username} \
      -e DB_PASSWORD=${db_password} \
      -e HOST=${host} \
      -e PORT=${port} \
      -e DATABASE=${database} \
      --name backend-app endgame-backend

  - docker build -t endgame-frontend ./frontend
  - docker rm -f frontend-app || true
  - docker run -d --restart always -p 80:8080 --name frontend-app endgame-frontend