#cloud-config
package_update: true
packages:
  - docker.io
  - git

runcmd:
  - systemctl enable docker
  - systemctl start docker

  - git clone https://github.com/katehjd21/endgame_assignment.git /home/ubuntu/app
  - cd /home/ubuntu/app

  - docker build -t endgame-frontend -f frontend/Dockerfile .
  - docker build -t endgame-backend -f backend/Dockerfile .

  - docker rm -f frontend || true
  - docker rm -f backend || true

  - docker run -d --restart always --name frontend -p 80:8080 endgame-frontend

  - docker run -d --restart always --name backend -p 8080:8080 endgame-backend
